<?php

return [

    [
        'name' => 'Avada',
        'original_source_url' => 'https://themeforest.net/item/avada-responsive-multipurpose-theme/2833226',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-premium-site-empresas-multisegmentos-avada/',
        'demo_url' => 'https://avada.theme-fusion.com/',
        'price_dollar' => 60,
        'price_real' => 33,
        'title' => 'Responsive Multi-Purpose Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'The7',
        'original_source_url' => 'https://themeforest.net/item/the7-responsive-multipurpose-wordpress-theme/5556590',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-the7/',
        'demo_url' => 'http://the7.io/',
        'price_dollar' => 39,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'BeTheme',
        'original_source_url' => 'https://themeforest.net/item/betheme-responsive-multipurpose-wordpress-theme/7758048',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-premium-site-empresas-multisegmentos-betheme/',
        'demo_url' => 'http://themes.muffingroup.com/betheme/',
        'price_dollar' => 59,
        'price_real' => 33,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template;responsive;multi;purpose',
    ],

    [
        'name' => 'Enfold',
        'original_source_url' => 'https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-site-empresas-multisegmentos-enfold/',
        'demo_url' => 'http://www.kriesi.at/themes/enfold-2017/',
        'price_dollar' => 59,
        'price_real' => 33,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'X',
        'original_source_url' => 'https://themeforest.net/item/x-the-theme/5871901',
        'source_url' => 'https://temaswordpressbr.com/',
        'demo_url' => 'https://theme.co/x/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Impreza',
        'original_source_url' => 'https://themeforest.net/item/impreza-retina-responsive-wordpress-theme/6434280',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-site-empresas-multisegmentos-impreza/',
        'demo_url' => 'http://impreza.us-themes.com/',
        'price_dollar' => 59,
        'price_real' => 33,
        'title' => 'Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Flatsome',
        'original_source_url' => 'https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-woocommerce-para-lojas-virtuais-wordpress-flatsome/',
        'demo_url' => '',
        'price_dollar' => 59,
        'price_real' => 33,
        'title' => 'Multi-Purpose Responsive WooCommerce Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Bridge',
        'original_source_url' => 'https://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-premium-site-empresas-multisegmentos-bridge/',
        'demo_url' => 'http://demo.qodeinteractive.com/bridge/',
        'price_dollar' => 60,
        'price_real' => 33,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template;responsive;multi;purpose',
    ],

    [
        'name' => 'Jupiter',
        'original_source_url' => 'https://themeforest.net/item/jupiter-multipurpose-responsive-theme/5177775',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-site-empresas-multisegmentos-jupiter/',
        'demo_url' => 'https://demos.artbees.net/jupiter/',
        'price_dollar' => 59,
        'price_real' => 33,
        'title' => 'Multi-Purpose Responsive Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Salient',
        'original_source_url' => 'https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-salient/',
        'demo_url' => 'http://themenectar.com/demo/salient/',
        'price_dollar' => 60,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Uncode',
        'original_source_url' => 'https://themeforest.net/item/uncode-creative-multiuse-wordpress-theme/13373220',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-uncode/',
        'demo_url' => 'https://undsgn.com/uncode/homepages/classic-agency/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Creative Multiuse WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'TheGem',
        'original_source_url' => 'https://themeforest.net/item/thegem-creative-multipurpose-highperformance-wordpress-theme/16061685',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-thegem/',
        'demo_url' => 'http://codex-themes.com/thegem/agency-one-pager/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Creative Multi-Purpose High-Performance WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Kallyas',
        'original_source_url' => 'https://themeforest.net/item/kallyas-responsive-multipurpose-wordpress-theme/4091658',
        'source_url' => 'https://www.astronautatemplates.com.br/produto/template-wordpress-site-empresas-multisegmentos-kallyas/',
        'demo_url' => 'https://demo.kallyas.net/',
        'price_dollar' => 69,
        'price_real' => 33,
        'title' => 'Creative eCommerce Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Kalium',
        'original_source_url' => 'https://themeforest.net/item/kalium-creative-theme-for-professionals/10860525',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-salient/',
        'demo_url' => 'http://themenectar.com/demo/salient/',
        'price_dollar' => 60,
        'price_real' => 33,
        'title' => 'Creative Theme for Professionals',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Total',
        'original_source_url' => 'https://themeforest.net/item/total-responsive-multipurpose-wordpress-theme/6339019',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-total/',
        'demo_url' => 'http://totaltheme.wpengine.com/base/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Shopkeeper',
        'original_source_url' => 'https://themeforest.net/item/shopkeeper-ecommerce-wp-theme-for-woocommerce/9553045',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-shopkeeper/',
        'demo_url' => 'http://shopkeeper.wp-theme.design/home/home-classic-1/',
        'price_dollar' => 69,
        'price_real' => 37,
        'title' => 'eCommerce WP Theme for WooCommerce',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'The Ark',
        'original_source_url' => 'https://themeforest.net/item/the-ark/19016121',
        'source_url' => 'https://temaswordpressbr.com/',
        'demo_url' => 'http://main.arktheme.com/',
        'price_dollar' => 29,
        'price_real' => 37,
        'title' => 'WordPress Theme made for Freelancers',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Massive Dynamic',
        'original_source_url' => 'https://themeforest.net/item/massive-dynamic-wordpress-website-builder/13739153',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-massive-dynamic/',
        'demo_url' => 'http://theme.pixflow.net/massive-dynamic/general/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'WordPress Website Builder',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'ListingPro',
        'original_source_url' => 'https://themeforest.net/item/listingpro-multipurpose-directory-theme/19386460',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-listingpro/',
        'demo_url' => 'http://studio.listingprowp.com/',
        'price_dollar' => 69,
        'price_real' => 37,
        'title' => 'Directory WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Oshine',
        'original_source_url' => 'https://themeforest.net/item/oshine-creative-multipurpose-wordpress-theme/9545812',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-oshine/',
        'demo_url' => 'http://oshinewptheme.com/v1/',
        'price_dollar' => 49,
        'price_real' => 37,
        'title' => 'Multipurpose Creative Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'ListGo',
        'original_source_url' => 'https://themeforest.net/item/listgo-directory-wordpress-theme/20254260',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-listgo/',
        'demo_url' => 'https://listgo.wiloke.com/',
        'price_dollar' => 39,
        'price_real' => 37,
        'title' => 'Directory WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Eduma',
        'original_source_url' => 'https://themeforest.net/item/education-wordpress-theme-education-wp/14058034',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-eduma/',
        'demo_url' => 'https://educationwp.thimpress.com/',
        'price_dollar' => 69,
        'price_real' => 37,
        'title' => 'Education WordPress Theme | Education WP',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Soledad',
        'original_source_url' => 'https://themeforest.net/item/soledad-multiconcept-blogmagazine-wp-theme/12945398',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-soledad/',
        'demo_url' => 'http://soledad.pencidesign.com/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Multi-Concept Blog/Magazine WP Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Porto',
        'original_source_url' => 'https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme/9207399',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-porto/',
        'demo_url' => 'http://www.newsmartwave.net/wordpress/porto/classic-original/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Responsive WordPress + eCommerce Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Ronneby',
        'original_source_url' => 'https://themeforest.net/item/ronneby-highperformance-wordpress-theme/11776839',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-ronneby/',
        'demo_url' => 'http://rnbtheme.com/home/',
        'price_dollar' => 49,
        'price_real' => 37,
        'title' => 'High-Performance WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Consulting',
        'original_source_url' => 'https://themeforest.net/item/consulting-business-finance-wordpress-theme/14740561',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-consulting/',
        'demo_url' => 'http://consulting.stylemixthemes.com/four/',
        'price_dollar' => 39,
        'price_real' => 37,
        'title' => 'Business, Finance WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Publisher',
        'original_source_url' => 'https://themeforest.net/item/publisher-magazine-blog-newspaper-and-review-wordpress-theme/15801051',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-publisher-better-studio/',
        'demo_url' => 'http://demo.betterstudio.com/publisher/',
        'price_dollar' => 39,
        'price_real' => 37,
        'title' => 'Newspaper Magazine AMP',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Houzez',
        'original_source_url' => 'https://themeforest.net/item/houzez-real-estate-wordpress-theme/15752549',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-houzez/',
        'demo_url' => 'http://houzez01.favethemes.com/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Real Estate WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'XStore',
        'original_source_url' => 'https://themeforest.net/item/xstore-responsive-woocommerce-theme/15780546',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-xstore/',
        'demo_url' => 'http://8theme.com/demo/xstore/',
        'price_dollar' => 49,
        'price_real' => 37,
        'title' => 'Responsive WooCommerce Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Composer',
        'original_source_url' => 'https://themeforest.net/item/composer-responsive-multipurpose-highperformance-wordpress-theme/13454476',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-composer/',
        'demo_url' => 'http://innwithemes.com/composer/composer-default/',
        'price_dollar' => 60,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose High-Performance WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Mag',
        'original_source_url' => 'https://themeforest.net/item/mag-full-featured-wordpress-magazine/20463212',
        'source_url' => 'https://temaswordpressbr.com/',
        'demo_url' => 'https://mnkythemes.com/mag/',
        'price_dollar' => 29,
        'price_real' => 37,
        'title' => 'Full Featured WordPress Magazine',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Stockholm',
        'original_source_url' => 'https://themeforest.net/item/stockholm-a-genuinely-multiconcept-theme/8819050',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-stockholm/',
        'demo_url' => 'http://demo.select-themes.com/stockholm1/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'A Genuinely Multi-Concept Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'REHub',
        'original_source_url' => 'https://themeforest.net/item/rehub-directory-multi-vendor-shop-coupon-affiliate-theme/7646339',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-rehub/',
        'demo_url' => 'http://rehub.wpsoul.com/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Price Comparison, Affiliate Marketing, Multi Vendor Store, Community Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Stack',
        'original_source_url' => 'https://themeforest.net/item/stack-multipurpose-wordpress-theme-with-variant-page-builder/19707359',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-stack-tommusrhodus/',
        'demo_url' => 'http://stack.tommusdemos.wpengine.com/homepages/home-landing-1/',
        'price_dollar' => 39,
        'price_real' => 37,
        'title' => 'Multi-Purpose WordPress Theme with Variant Page Builder & Visual Composer',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'HyperX',
        'original_source_url' => 'https://themeforest.net/item/hyperx-portfolio-for-freelancers-agencies/13439786',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-hyperx/',
        'demo_url' => 'http://wp-royal.com/hyper-x/ares/',
        'price_dollar' => 16,
        'price_real' => 37,
        'title' => 'Responsive Wordpress Portfolio Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Brooklyn',
        'original_source_url' => 'https://themeforest.net/item/brooklyn-responsive-multipurpose-wordpress-theme/6221179',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-brooklyn/',
        'demo_url' => 'http://themeforest.unitedthemes.com/wpversions/brooklyn/demo23/',
        'price_dollar' => 29,
        'price_real' => 37,
        'title' => 'Creative Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Infinite',
        'original_source_url' => 'https://themeforest.net/item/infinite-responsive-multipurpose-wordpress-theme/16869357',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-infinite/',
        'demo_url' => 'https://demo.goodlayers.com/infinite/',
        'price_dollar' => 60,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Motors',
        'original_source_url' => 'https://themeforest.net/item/motors-automotive-cars-vehicle-boat-dealership-classifieds-wordpress-theme/13987211',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-motors/',
        'demo_url' => 'http://motors.stylemixthemes.com/',
        'price_dollar' => 79,
        'price_real' => 37,
        'title' => 'Automotive, Cars, Vehicle, Boat Dealership, Classifieds WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Boo',
        'original_source_url' => 'https://themeforest.net/item/boo-responsive-multipurpose-theme-/16993787',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-boo/',
        'demo_url' => 'http://boo.themerella.com/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Responsive Multi-Purpose Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Pearl',
        'original_source_url' => 'https://themeforest.net/item/pearl-true-multiniche-wordpress-theme/20432158',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-pearl-wp/',
        'demo_url' => 'http://pearl.stylemixthemes.com/',
        'price_dollar' => 29,
        'price_real' => 37,
        'title' => 'Micro-niche Business WordPress Themes Bundle',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'JobCareer',
        'original_source_url' => 'https://themeforest.net/item/jobcareer-job-board-responsive-wordpress-theme/14221636',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-jobcareer/',
        'demo_url' => 'http://jobcareer.chimpgroup.com/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Job Board Responsive WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Photography',
        'original_source_url' => 'https://themeforest.net/item/photography-responsive-photography-theme/13304399',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-photography/',
        'demo_url' => 'http://themes.themegoods.com/photography/landing/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Responsive Photography Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'WPLMS',
        'original_source_url' => 'https://themeforest.net/item/wplms-learning-management-system/6780226',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-wplms/',
        'demo_url' => 'http://themes.vibethemes.com/wplms/skins/ms/',
        'price_dollar' => 64,
        'price_real' => 37,
        'title' => 'Learning Management System for WordPress, Education Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Zox News',
        'original_source_url' => 'https://themeforest.net/item/zox-news-professional-wordpress-news-magazine-theme/20381541',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-zox-news/',
        'demo_url' => 'http://www.mvpthemes.com/zoxnews/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Professional WordPress News & Magazine Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'WP Residence',
        'original_source_url' => 'https://themeforest.net/item/wp-residence-real-estate-wordpress-theme/7896392',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-wp-residence/',
        'demo_url' => 'http://wpresidence.net/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Residence Real Estate WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Bimber',
        'original_source_url' => 'https://themeforest.net/item/bimber-viral-buzz-wordpress-theme/14493994',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-bimber/',
        'demo_url' => 'http://original.bimber.bringthepixel.com/',
        'price_dollar' => 59,
        'price_real' => 37,
        'title' => 'Viral Magazine WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Business Lounge',
        'original_source_url' => 'https://themeforest.net/item/businesslounge-multipurpose-business-consulting-theme/20587127',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-rt-theme-23-business-lounge-v1-0/',
        'demo_url' => 'http://businesslounge-demo.rtthemes.com/',
        'price_dollar' => 39,
        'price_real' => 37,
        'title' => 'Multi-Purpose Business & Consulting Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Fusion',
        'original_source_url' => 'https://themeforest.net/item/fusion-creative-multipurpose-wordpress-theme/20320094',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-fusion-themeluxe/',
        'demo_url' => 'http://fusion.themeluxe.com/portfolio/',
        'price_dollar' => 29,
        'price_real' => 37,
        'title' => 'Creative Multi-Purpose WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Travel Tour',
        'original_source_url' => 'https://themeforest.net/item/travel-tour-travel-tour-management-system-wordpress-theme/19423474',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-travel-tour/',
        'demo_url' => 'https://demo.goodlayers.com/traveltour/',
        'price_dollar' => 65,
        'price_real' => 37,
        'title' => 'Tour Booking, Travel WordPress Theme',
        'tags' => 'wordpress;template',
    ],

    [
        'name' => 'Newsmag',
        'original_source_url' => 'https://themeforest.net/item/newsmag-news-magazine-newspaper/9512331',
        'source_url' => 'https://temaswordpressbr.com/downloads/tema-newsmag/',
        'demo_url' => 'https://demo.tagdiv.com/newsmag/',
        'price_dollar' => 49,
        'price_real' => 37,
        'title' => 'News Magazine Newspaper',
        'tags' => 'wordpress;template',
    ],

];
